cimplec/sim-c

simc-codes/q4.simc
Simc code for Question 4
Closes : #46
=> Issue 46 : Added Q4 Simc Code (Check Even or Odd)

simc-codes/q1.simc
Defined and printed a string in Simc.
Closes: #43
=> Issue:43 - Q1 Added (define and print string)

simc-codes/q14.simc
=> Add code for Q14

simc-codes/q49.sim, simc-codes/q49.simc
=> Add code for Q49

simc-codes/q46.simc, simc-codes/q6.simc
Solution for q6 is added to the simc-codes directory
=> Solution for q6 is added

simc-codes/q9.simc
Solution for q9 is added in simc-codes
=> Added solution for q9

simc-codes/q12.simc
Solution for q12 is added in simc-codes
=> Added solution for q12

simc-codes/q16.simc
=> Added code for q16

simc-codes/q51.simc
solves #97.
While solving the above program, I encountered issues while chaining operators in expressions, such as (x1-x2)^(x1-x2), which is why I've solved this in this manner. But please do see whether it's an issue or not. I got the error "assignment operator after identifier expected" for the example expression
=> solution for q51

simc-codes/q41.simc
=> Code for question number 41

simc-codes/q43.simc
Added code for smith number, question 43, issue #90
=> [FEATURE][CODE] Smith number program in simc

simc-codes/q23.simc
=> added q23.simc

simc-codes/q38.simc
=> Added answer to question 38

simc-codes/q26.simc
Solves #71 
Please review! Thanks :)
=> Added q26.simc

simc-codes/q24.simc
=> solution for q24

simc-codes/q29.simc
=> solution for q29

simc-codes/q28.simc
=> solution for q28

simc-codes/q37.simc
=> Added solution to Question 37

simc-codes/q33.simc
Added simC code for question 33 #78 
Compute the value of the following series till the nth term.
=> Added simC code for question 33 #78

simc/simc_parser.py
Fixed issue #133 , for loop now accepting variables as starting ,ending variables and changing variable
changes in simc-parser.py
**Tests**
simc code:
```bash
MAIN
var a =0
var b =10
var c =5
for i in a to b by +c{
print(i)
}
END_MAIN
```
C code generated:
```bash
#include <stdio.h>
int main() {
int a = 0;
int b = 10;
int c = 5;
for(int i = a; i < b; i+=c) {
printf("%d", i);
}
return 0;
}
```
=> [FIX] for loop 

simc-codes/q35.simc
=> added q35.simc

simc-codes/q19.simc
Added q19.simc, which takes in a binary number and converts it to its decimal equivalent.
=> Created q19.simc

simc-codes/q53.simc
Solve #161 by proposing a solution for question 53
=> Add solution for question 53

simc-codes/q74.simc
Implements: https://github.com/cimplec/sim-c/issues/180
=> [in-180] Added Sample Program to Calculate Volume Of Cone

simc-codes/q18.simc
Program to check if a number is a palindrome implemented. The generated .c file corresponding to the sims file was generated compiled and tested for the functionality.
=> q18 program implemented

simc-codes/q73.simc
Added the answer to question 73. Using the built in C constant of PI
=> [in-179] Created q73.simc, finding volume of sphere 

simc-codes/q59.simc
_Code for finding area of a circle when value of radius is taken in as input and constant pi is defined in the code_
=> [in-59] Added code for Q59, Area of a Circle

simc-codes/q60.simc
_Created a q60.simc solution that takes radius as input and finds circumference for that circle, constant is declared in the code_
=> [in-168] Code for Q60, Circumference of a Circle

simc-codes/q58.simc
_Finding the Average of 7 numbers when average of 6 numbers and 7th number is given._
=> [in-166] Added code for Q58, Finding Avg of 7 num

simc-codes/q69.simc
_This code takes a binary number as a string as input and outputs its Octal representation
_First Binary is converted into Decimal format and Decimal is then converted into Octal representation.__
=> [in-175] Added Code for Q69, Binary to Octal

simc-codes/q71.simc
The user inputs a valid month of the year in int format, the script prints the month in English format
=> [in-177] Added Code for Q71, Month in a Year

simc-codes/q57.simc
=> simC code for question 57

simc-codes/q66.simc
_the script takes a valid octal number as input and returns decimal representation of the same_
_with added code that safe cases for non octal numbers_
=> [In-172] Added Code for Q66, Octal to Decimal 

simc-codes/q20.simc
_A script that takes a decimal number as input and returns its binary representation_
=> [in-62] Added Code for Q20, Decimal to Binary

simc-codes/q30.simc
simc code for series pertaining to question 30 written and its counterpart c code was tested for output.
=> Question 30 code written and tested

simc-codes/q77.simc
Write simC code for question 77, as described in #229 
I've added an optional if statement for formatting reasons which isn't part of the solution
Thank you for the opportunity to dig into this project 😊
=> [in-229] Write simC code for question 77

simc-codes/q81.simc
Made the switching by assigning one of the variables as a sum of the others. From there we can subtract the variables from the  sum to get the swap.
=> [in-233] Created q81.simc, swapping two variables without using a third

simc-codes/q79.simc
Print numbers between 1 to 100 which are divisible by 3 or 5 or both
=> Added solution for q79:Multiples of 3 and 5

simc/lexical_analyzer.py
I have added the following escape sequences
`['\\','\0','\n','\a','\b','\e','\f','\r','\t','\v','\?','\'','\"']`
Closes #243
=> [Code] Added escape sequences

simc-codes/q61.simc
This simc code prints the american flag, it uses two while loops to
print the two parts of the American Flag.
Signed-off-by: Puranjay Mohan <puranjay12@gmail.com>
=> Simc-codes: Added code for Q61 - American Flag

simc-codes/q48.simc
This simc code checks if the double input is greater than or
equal to 1000000000 and less than or equal to 9999999999
and if this condition is satisfied then it is valid
Signed-off-by: Puranjay Mohan <puranjay12@gmail.com>
=> Simc-codes: Added code for Q48 - Valid Phone Number

simc-codes/q68.simc
This simc code converts a binary number to its hexadecimal
representation.
Signed-off-by: Puranjay Mohan <puranjay12@gmail.com>
=> Simc-codes: Added code for Q68 - Binary to Hexadecimal

simc/compiler.py, simc/simc_parser.py
Fixes #257
Now any return statements outside functions generate error.
Also return statements inside main functions are supported now.
=> BugFix : Make sure return statements are inside functions

simc-codes/q90.simc
=> q90 - Ireland flag

simc-codes/q94.simc
solve the issue #273 i hope everything was right :)
Happy hacktoberfest
=> Convert cm to inch and foot #273

simc-codes/q95.simc
This will solve #300 .
Used
Float input
conditional (if else), relational(>,<) and logical(&&) operator to judge the
printing with variables embedded in strings
=> Added program for q95

simc/compiler.py, simc/lexical_analyzer.py, simc/simc_parser.py
Added the following math constants to simc
Fixes #202 
```
C Name->SIMC Name
M_PI ->PI
M_E -> E
INFINITY -> inf
NAN ->NaN
```
Test CODE:
```simc
MAIN
print(inf)
print(E)
print(PI)
print(NaN)
print(-inf)
END_MAIN
```
=> [FEATURE] Added math constants to simc

simc-codes/q34.simc
Created q34.simc for concatenating two strings as assigned in #79
=> Added q34.simc

simc-codes/q99.simc
Added solution for harmonic mean problem as assigned in #304
=> Added q99.simc

simc-codes/q75.simc
=> Added solution question 75 Simc-codes (q75)

simc-codes/q201.simc
=> Added solution for question 201

simc/global_helpers.py, simc/simc.py
=> Fix: leaking out colors in terminal 

simc/simc.py
=> fixed the bug #350

simc/compiler.py, simc/lexical_analyzer.py, simc/op_code.py, simc/simc_parser.py, simc/token_class.py
resolves #344 
Tested codes:
simc:
```
var a = "a"
var i = '4.0'
array immm[30] = {"aaa", "bbbb"}
//print(immm[0])
```
simc:
```
fun sum(i, j) {
return i  + j
}
MAIN
var i = 4
array numbers[30] = {i, sum(i, i), 2}
END_MAIN
```
Output: c code
simc:
```
MAIN
var i = 4
array numbers[30] = {i, 1, 2}
END_MAIN
```
Output: c code
```
int i = 4;
int numbers[30] = {i, 1,2};
```
simc:
```
MAIN
array numbers[30]
END_MAIN
```
Output: c code
`declared numbers[30];`
simc code:
```
MAIN
var i = 'a'
array numbers[30] = {a, 2}
END_MAIN
```
Output: Error, multiple types
=> In-344 Add declaration of array

simc/compiler.py
=> Revert "Modified compiler.py"

simc-codes/q104.simc
@Math-O5 Added solution for question 104 for issue #372
=> Added solution for question 104

simc-codes/q104.simc, simc-codes/q105.simc
@Math-O5 Added code for problem 105 of issue #373
=> Added code for problem 105

simc-codes/q112.simc
Issue: #379 
Find the area of the circumcircle of square.
=> Solved question 112

simc-codes/q104.simc, simc-codes/q107.simc
I have added the solution of problem 107 for issue #375
=> Added code for q107

simc/compiler.py, simc/lexical_analyzer.py, simc/parser/simc_parser.py, simc/parser/struct_parser.py
=> In 356 & 357 - Added support for structure declaration and instantiation in the definition

simc/compiler.py, simc/lexical_analyzer.py, simc/parser/simc_parser.py, simc/parser/struct_parser.py
@Math-O5  please confirm if this PR is fine?
=> In356 357 -Added support for structure declaration and instantiation in the definition

simc/parser/conditional_parser.py, simc/parser/function_parser.py, simc/parser/loop_parser.py, simc/parser/struct_parser.py
=> In 417 - Incorrect Use Of "found_right_brace"

simc/parser/conditional_parser.py
=> In 420 - Added support for newline in switch_statement

simc-codes/q113.simc
Closes #380 
Added the code for q113
=> Added simC code for q113.

simc/lexical_analyzer.py, simc/simc.py
- Converted lexical analyzer to a class.
- Made all methods except lexical_analyze and update_filename private.
- Meaningul variable names.
- Fixed comments.
- Reduced redundant code into methods.
=> Cleanup lexical anaylzer

simc/global_helpers.py, simc/op_code.py, simc/simpack.py, simc/symbol_table.py, simc/token_class.py
- Add meaningful comments.
- Remove unecessary functions (token2dig in token_class.py and opcode2dig in op_code.py.
=> Refactor global helpers, opcode, token, symbol table and simpack

simc/global_helpers.py, simc/parser/array_parser.py, simc/parser/simc_parser.py, simc/parser/variable_parser.py
Updated the following parsing functions:-
- Print statement
- Import statement
- Variable and array declaration (+ assignment)
=> Increase readability of parser code

simc/parser/simc_parser.py
Increase readability for:-
- Variable parsing
- Unary statement parsing
=> Increase code readability

simc/global_helpers.py, simc/parser/array_parser.py, simc/parser/function_parser.py, simc/parser/loop_parser.py, simc/parser/simc_parser.py, simc/parser/struct_parser.py, simc/parser/variable_parser.py
Increase readability in parsing for:-
- While loop
- Do while loop
- For loop
- MAIN, END_MAIN
- Structure (Declaration + Instantiation)
- Function definition
=> Make code readable

simc/parser/conditional_parser.py, simc/parser/simc_parser.py
Increase readability of parsing for:-
- Unary statements
- Default statement (in switch case)
- Case statement (in switch case)
- Switch case
- Break statement
- Continue statement
- If, else if, else
- Exit statement
=> Increase readability of parser

simc-codes/q114.simc
made the changes you asked for .
=> Added a feature (question number114)

simc/parser/simc_parser.py
=> Revert "Add flag 'scope_mapping' to mark the current scope(GLOBAL, FUN, MAIN,…"

simc/simc.py, simc/symbol_table.py
This Pull Request is part of SWoC 2021.
Closes #478
**Implementation details**
Used Magic Function _ _ str _ _( ) to print the Symbol Table in an organised manner
**simC Code**
MAIN
print( "Hello World\n" )
var a = input( "Enter integer: ", "i" )
a = a * 2
print( "Double of integer: {a}" )
END_MAIN
Number of Unit Tests Passing: 273
Number of Code Tests Passing: 106
=> Symbol Table looks more presentable. Used magic functions
